runtime: python39

env_variables:
  CLOUD_SQL_CONNECTION_NAME: ''
  CLOUD_SQL_USERNAME: ''
  CLOUD_SQL_PASSWORD: ''
  CLOUD_SQL_DATABASE_NAME: ''
  
# Handlers Configuration
handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto